on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  compile_program:
    name: Compile Program and installers
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: macos-latest
          - os: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Gradle
      run: ./gradlew packageMyApp
    - name: Upload idL Windows artifact
      if: matrix.config.os == 'windows-latest' 
      uses: actions/upload-artifact@v1.0.0
      with:
        name: idL-windows
        path: build/
    - name: Upload macOs artifact
      if: matrix.config.os == 'macos-latest' 
      uses: actions/upload-artifact@v1.0.0
      with:
        name: idL-macOs
        path: build/
    - name: Javadoc
      run: ./gradlew javadoc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/