on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  compile_program:
    name: Compile Program and installers
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: macos-latest
          - os: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Gradle
      run: ./gradlew packageMyApp
    - name: Upload idL Windows artifact
      if: matrix.config.os == 'windows-latest' 
      uses: actions/upload-artifact@v1.0.0
      with:
        name: idL-windows
        path: |
          build/
          !build/assets/
          !build/distributions/
          !build/launch4j/
          !build/resources/
          !build/tmp/
          !build/classes/
          !build/generated/
    - name: Upload macOs artifact
      if: matrix.config.os == 'macos-latest' 
      uses: actions/upload-artifact@v1.0.0
      with:
        name: idL-macOs
          build/
          !build/assets/
          !build/distributions/
          !build/launch4j/
          !build/resources/
          !build/tmp/
          !build/classes/
          !build/generated/